apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 5
  selector:
    matchLabels:
      type: backend
  template:
    metadata:
      labels:
        type: backend
    spec:
      containers:
        - name: container1
          image: rohinidocker550/flask:latest
          ports:
            - containerPort: 4000
              protocol: TCP
